import{i as p}from"./assets/vendor-ad859c2f.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const o of t.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&a(o)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const g="44952732-afe4551e0894d66c0b6ee4476";function y(i){const n=`https://pixabay.com/api/?key=${g}&q=${i}&image_type=photo&orientation=horizontal&safesearch=true`;return fetch(n).then(s=>{if(!s.ok)throw new Error(s.status);return s.json()})}function h(){p.show({message:"Sorry, there are no images matching your search query. Please try again!"})}const r={submitBtn:document.querySelector(".js-submit-btn"),form:document.querySelector("form[data-form]"),input:document.querySelector("input[data-input]"),gallery:document.querySelector(".gallery")};r.submitBtn.addEventListener("click",i=>{i.preventDefault();const n=r.input.value.trim(),s=r.input.value;function a(){return n===""?(r.submitBtn.disabled=!0,console.log("input is empty"),h(),!0):(r.submitBtn.disabled=!1,!1)}function e({webformatURL:o,largeImageURL:c,tags:u,likes:l,views:m,comments:f,downloads:d}){return`<div class="image-card">
    <img src="${c}" alt= "${u}" />
    <div class="info">
    <p>Likes: ${l}</p>
    <p>Views: ${m}</p>
    <p>Comments: ${f}</p>
    <p>Downloads: ${d}</p>
    </div>
  </div>`}function t(o){const c=o.hits;let u="";c.forEach(l=>{u+=e(l)}),r.gallery.innerHTML=u}if(r.gallery.innerHTML="",r.form.reset(),a()){r.submitBtn.disabled=!1;return}y(s).then(t).catch(o=>{console.error("No Images",o)})});
//# sourceMappingURL=commonHelpers.js.map
